# Array Attributes part-1

In [3]:
# numpy attributes
import numpy as np

arr1 = np.arange(10,dtype=np.int32)
arr2 = np.arange(12,dtype=float).reshape(3,4)
arr3 = np.arange(8).reshape(2,2,2)

arr3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
# ndim : tells you the number of dimensions (axes) of a NumPy array.

arr3.ndim

3

In [9]:
# shape : tells you how many elements are present in each dimension.

arr3.shape

(2, 2, 2)

In [12]:
# size : tells you the total number of elements present in a NumPy array.

print(arr2.size)
arr2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [11]:
# itemsize : tells you how many bytes are used to store ONE element of a NumPy array.

arr3.itemsize

8

In [ ]:
# dtype means data type

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
float64
int64


# Changing Data type

In [ ]:
# astype : used to convert the data type (dtype) of a NumPy array.

arr3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [16]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# 1. Scalar Opearations


In [ ]:

print(a1 + 5)
print(a1 - 6)
print(a1 * 3)
print(a1 / 3)


[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[-6 -5 -4 -3]
 [-2 -1  0  1]
 [ 2  3  4  5]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
[[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]]


# 2. Vector Operations  

In [ ]:

""" In NumPy, vector operations mean performing mathematical operations
 directly on arrays/vectors without explicitly writing for loops. """

print(a1 + a2)
print(a2 - a1)
print(a1 * a2)
print(a1 / a2)



[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


# Numpy Array Functions

In [5]:
import numpy as np

ar1 = np.random.random((3,3))
ar1 = np.round(ar1*100) # np.round() is used to round decimal numbers to a specified number of decimal places.
ar1 # by default it is 0 but we can decide as well like (array, decimal places)

array([[100.,  21.,  87.],
       [  9.,  61.,   8.],
       [ 73.,  39.,  38.]])

 # 1. max, min, sum, prod

In [ ]:
# There are important parameters that are used in these below functions axis and keepdims

# axis : Specifies the axis along which to perform the operation like (axis=0,1,None) # 0 means column-wised # 1 means row-wised

# keepdims : Retains reduced dimensions (True, False)


# max : In NumPy, the np.max() function is used to find the maximum (largest) value in an array.

max = np.max(ar1)
print(max)

# min : In NumPy, the np.min() function is used to find the minimum (smallest) value in an array.
min = np.min(ar1)
print(min)

# sum : The np.sum() function calculates the sum of all elements in an array or the sum along a specified axis.

sum = np.sum(ar1)
print(sum)

# prod : The np.prod() function calculates the product (multiplication) of all elements in an array or along a specified axis.
 
prod = np.prod(ar1)
print(prod)

100.0
8.0
436.0
86810437022400.0


# 3. mean, median, standard deviation and variance

In [ ]:
# There are important parameters that are used in these below functions axis and keepdims

# axis : Specifies the axis along which to perform the operation like (axis=0,1,None) # 0 means column-wised # 1 means row-wised

# keepdims : Retains reduced dimensions (True, False)


arr = np.array([20,40,60,80,100])

# mean
mean = np.mean(arr)   
print(mean)

# median
median = np.median(arr)
print(median)

# std
std = np.std(arr)
print(std)

# var
var = np.var(arr)
print(var)


60.0
60.0
28.284271247461902
800.0


# Trigonometry Functions

In [16]:
# sin, cos, tan, arcsin, arccos, arctan

# arcsin : inverse sin

sin = np.sin(ar1)
print(sin)

cos = np.cos(ar1)
print(cos)

tan = np.tan(ar1)
print(tan)

inverse_sin = np.arcsin(ar1)
print(inverse_sin)

inverse_cos = np.arccos(ar1)
print(inverse_cos)

inverse_tan = np.arctan(ar1)
print(inverse_tan)


[[-0.50636564  0.83665564 -0.82181784]
 [ 0.41211849 -0.96611777  0.98935825]
 [-0.67677196  0.96379539  0.29636858]]
[[ 0.86231887 -0.54772926  0.56975033]
 [-0.91113026 -0.25810164 -0.14550003]
 [-0.73619272  0.26664293  0.95507364]]
[[-0.58721392 -1.52749853 -1.44241747]
 [-0.45231566  3.74316794 -6.79971146]
 [ 0.9192864   3.61455441  0.31030966]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
[[1.56079666 1.52321322 1.55930258]
 [1.46013911 1.55440435 1.44644133]
 [1.55709855 1.54516092 1.54448661]]


C:\Users\Dell\AppData\Local\Temp\ipykernel_20176\3168636119.py:14: RuntimeWarning: invalid value encountered in arcsin
  inverse_sin = np.arcsin(ar1)
C:\Users\Dell\AppData\Local\Temp\ipykernel_20176\3168636119.py:17: RuntimeWarning: invalid value encountered in arccos
  inverse_cos = np.arccos(ar1)
