# Array Attributes part-2

# Dot Product 

In [3]:
import numpy as np

a1 = np.arange(12).reshape(4,3)
a2 = np.arange(12,24).reshape(3,4)

dot_product = np.dot(a1,a2)
print(dot_product)

print(a1@a2)

[[ 56  59  62  65]
 [200 212 224 236]
 [344 365 386 407]
 [488 518 548 578]]
[[ 56  59  62  65]
 [200 212 224 236]
 [344 365 386 407]
 [488 518 548 578]]


# log and exponents

In [ ]:

# log : The np.log() function calculates the natural logarithm of a number, using base

a3 = np.array([1, 2, 4, 8, 16, 32])
log = np.log(a3)
print(log)

# The np.log2() function calculates the logarithm of a number with base 2.
# The np.log10() function calculates the logarithm of a number with base 10.

# exp : The np.exp() function calculates e raised to the power of each input element.

np.exp(a3)

# The np.exp2() function calculates 2 raised to the power of each element.
# The np.power() function raises each element of a base array to the corresponding exponent.
# The np.float_power() function is similar to np.power(), but promotes its inputs to floating-point types to calculate the result.


[0.         0.69314718 1.38629436 2.07944154 2.77258872 3.4657359 ]


array([2.71828183e+00, 7.38905610e+00, 5.45981500e+01, 2.98095799e+03,
       8.88611052e+06, 7.89629602e+13])

# floor, round, ceil

In [25]:
# round : The np.round() function rounds numbers to a specified number of decimal places.
# np.round(a, decimals=0, out=None) parameters

a = np.array([1.2, 2.5, 3.7, 4.8])
print(np.round(a))

aa = np.array([1.2345, 2.5678, 3.14159]) # Positive decimal places
print(np.round(aa, decimals=2)) 

aaa = np.array([123, 456, 789]) # Negative decimal places
print(np.round(aaa, decimals=-1))
print(np.round(aaa, decimals=-2))

# floor : The np.floor() function returns the greatest integer less than or equal to the input value.
# np.floor() returns floating-point values for floating-point inputs, even when the results are whole numbers.

flr = np.array([1.2, 2.7, 3.9, 4.1])
print(np.floor(flr))

# ceil : The np.ceil() function returns the smallest integer greater than or equal to the input value.
# Unlike floor, ceiling always rounds toward positive infinity.

cl = np.array([1.2, 2.7, 3.9, 4.1]) # positive values
print(np.ceil(cl))

c2 = np.array([-1.2, -2.7, 2.7, 3.9]) # negative values
print(np.ceil(c2))


[1. 2. 4. 5.]
[1.23 2.57 3.14]
[120 460 790]
[100 500 800]
[1. 2. 3. 4.]
[2. 3. 4. 5.]
[-1. -2.  3.  4.]
