### NUMPY BASICS 

# Use library 

-> import numpy as np

In [ ]:
#How to create numpy array

import numpy as np

a = np.array([1,2,3]) # (np.array)  1D Array

print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1,2,3],[4,5,6]]) # 2D Array
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3D Array
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [3]:
# dtype

import numpy as np

np.array([1,2,3],dtype = bool) 
# np.array([1,2,3],dtype = float)
# np.array([1,2,3],dtype = complex) 

array([ True,  True,  True])

In [4]:
# np.arange -- it works like range in for loop 

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [5]:
# with reshape :- used to change the shape of an array without changing its data

np.arange(1,11).reshape(5,2) # 5 - rows, 2 - columns   # helps to create matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
# np.ones and np.zeros

np.ones((3,4)) # Creates an array where every element is 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4)) # # Creates an array where every element is 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random : used to generate random numbers and random data.

x = np.random.random((3,4)) 
print(x)

[[0.65236875 0.44258072 0.43068944 0.45429839]
 [0.04773929 0.97543605 0.76103109 0.82859659]
 [0.29210465 0.28195185 0.76421715 0.13322395]]


In [ ]:
# np.linspace : creates an array of evenly spaced numbers between a starting value and an ending value.

np.linspace(-10,10,10) # (start, stop, num) # num : how many number you want

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity : np.identity() creates an identity matrix.

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# reshape : np.reshape(array, new_shape)

a = np.array([1, 2, 3, 4, 5, 6])

b = np.reshape(a, (3, 2))

print(b)

[[1 2]
 [3 4]
 [5 6]]
