# INDEXING AND SLCING

In [ ]:
import numpy as np 

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Indexing

In [ ]:
print(a1) # 1D array
print(a1[-1])

[0 1 2 3 4 5 6 7 8 9]
9


In [ ]:
# 2D array : In a 2D array, you use two indices: one for the row and one for the column
# array[row_index, column_index]

print(a2) 
print("indexing: ", a2[2][:])
print("indexing: ", a2[2][3])
print("indexing: ", a2[1,3]) # this method is only for numpy array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
indexing:  [ 8  9 10 11]
indexing:  11
indexing:  7


In [17]:
# 3D array 

print(a3)
print("Indexing: ", a3[1,0,1])
print("Indexing: ", a3[0,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Indexing:  5
Indexing:  2


# Slicing

In [ ]:
# (start, stop, steps) # 1D array
print(a1)
print(a1[2:8])
print(a1[2:8:2])
print(a1[0:])
print(a1[:-1])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]


In [ ]:
# 2D array # (row, column)

print(a2)
print("Slicing: ",a2[:,2])
print("Slicing: ",a2[0,:])
print("Slicing: ",a2[1:,1:3])
print("Slicing: ",a2[1:,1:])
print("Slicing: ",a2[::2,::3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Slicing:  [ 2  6 10]
Slicing:  [0 1 2 3]
Slicing:  [[ 5  6]
 [ 9 10]]
Slicing:  [[ 5  6  7]
 [ 9 10 11]]
Slicing:  [[ 0  3]
 [ 8 11]]


In [46]:
# 3D array

a3 = np.arange(27).reshape(3,3,3) # (2d array, row, column)

print(a3) 
print("Slicing: \n\n",a3[1])
print("Slicing: \n\n",a3[::2])
print("Slicing: \n\n",a3[1,:,1])
print("Slicing: \n\n",a3[::2,2,2])
print("Slicing: \n\n",a3[::2,-1,-1])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Slicing: 

 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
Slicing: 

 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Slicing: 

 [10 13 16]
Slicing: 

 [ 8 26]
Slicing: 

 [ 8 26]
