# Iteration on Numpy Array

-> Iteration in NumPy means accessing the elements of an array one by one using loops. It is useful for processing, modifying and analyzing array data.

-> NumPy supports iteration over 1D, 2D and multidimensional arrays.

In [16]:
import numpy as np 

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

In [13]:
print(a1)
for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [14]:
for i in a2:
    print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
for i in a3:
    print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
for i in np.nditer(a3):
    print(iter) # nditer stands for N-dimensional iterator.

<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>


# Reshaping, Transporse, Ravel

-> Reshaping is the process of changing the dimensions of an array without changing the number or order of its elements.

-> Transpose is the operation of interchanging the axes of an array. For a 2D array, it swaps rows and columns.

-> Ravel converts a multidimensional array into a one-dimensional array.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

b = np.reshape(a, (2, 3)) # reshape

print(b)

trans = np.transpose(b)
#a.T   # transporse  we can write like this also - array_name.T
print("transporse:\n ", trans)  


ravel = np.ravel(a) # multi-dimensional to 1D
print("Ravel: \n", ravel)

[[1 2 3]
 [4 5 6]]
transporse:
  [[1 4]
 [2 5]
 [3 6]]
Ravel: 
 [1 2 3 4 5 6]


# Stacking and Splitting in NumPy

-> Stacking and splitting are NumPy operations used to combine multiple arrays into a single array or divide an array into multiple smaller arrays.

Stacking: Combines two or more arrays.

Splitting: Divides an array into multiple smaller arrays.

# Stacking

In [29]:
# np.stack() : np.stack() joins multiple arrays along a new axis.
# stack = np.stack(a, axis=0)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.stack((a, b)) # 1D Array

print(c)
print(c.shape)

# np.vstack() : np.vstack() stacks arrays vertically, meaning it combines them row-wise.
# np.vstack(tup)

d = np.vstack((a, b)) # 1D array

print(d)
print(d.shape) 

e = np.array([[1, 2],   # 2D array
              [3, 4]])

f = np.array([[5, 6],
              [7, 8]])

print(np.vstack((e, f)))


# np.hstack() : np.hstack() stacks arrays horizontally.
# np.hstack(tup)

g = np.array([1, 2, 3])  # 1D array
h = np.array([4, 5, 6])

i = np.hstack((g, h))

print(i)


j = np.array([[1, 2],
              [3, 4]])

k = np.array([[5, 6],
              [7, 8]])

print(np.hstack((j, k)))


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


# Splitting

In [30]:
# np.split() : np.split() divides an array into multiple sections.
# np.split(ary, indices_or_sections, axis=0)

a = np.array([10, 20, 30, 40, 50, 60])

b = np.split(a, 3)

print(b)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [ ]:
# Split using indices

a = np.array([10, 20, 30, 40, 50, 60])

b = np.split(a, [2, 4]) # 2 and 4 are split positions

print(b)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [32]:
# Split a 2D array

a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

b = np.split(a, 2, axis=0)

for x in b:
    print(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [33]:
# np.array_split(): divides an array into a specified number of sections, even if the sections cannot all be equal in size.
# np.array_split(ary, indices_or_sections, axis=0)

a = np.array([10, 20, 30, 40, 50])

b = np.array_split(a, 3)

print(b)

[array([10, 20]), array([30, 40]), array([50])]


In [34]:
# np.vsplit() splits an array vertically, along the row axis.
# np.vsplit(ary, indices_or_sections)

a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

b = np.vsplit(a, 2)

print(b)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [35]:
# np.hsplit() splits an array horizontally, along the column axis for 2D arrays.
# np.hsplit(ary, indices_or_sections)

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

b = np.hsplit(a, 2)

print(b)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
