# Numpy array v/s Python list 

# speed

In [10]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []

import time

start = time.time()

for i in range(len(a)):
    c.append(a[i] + b[i])

end = time.time()

print("Execution time:", end - start, "seconds")

Execution time: 1.6450660228729248 seconds


In [ ]:
#numpy : numpy is much faster than python list

import numpy as np
import time

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()

c = a + b

end = time.time()

print("Execution time:", end - start, "seconds")

Execution time: 0.02786564826965332 seconds


# memory

In [ ]:
# list

a = [i for i in range(10000000)]

import sys

sys.getsizeof(a)

89095160

In [ ]:
# numpy : we can reduce the size of memory by using dtype= np.int32,16,8,3 like that
a = np.arange(10000000, dtype=np.int64) 
sys.getsizeof(a)


80000112

# Advance Indexing

In [7]:
# Normal Indexing and Slicing

import numpy as np

a = np.arange(12).reshape(4,3)
print(a)
print("indexing: ", a[2])
print("Slicing: ", a[5:])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
indexing:  [6 7 8]
Slicing:  []


# fancy indexing

In [18]:
a = np.arange(24).reshape(6,4)
print(a)
print("row-wise:\n ",a[[0,2,3]]) # if i need 0th, 2nd and 3rd row in the array
print("column-wise:\n ",a[:,[0,2,3]]) # if i need columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
row-wise:
  [[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]
column-wise:
  [[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


# boolean indexing

In [ ]:
import numpy as np

# randint() is a function used to generate random integers. In NumPy, it belongs to the random module.
# np.random.randint(low, high=None, size=None)

a = np.random.randint(1, 100, 24).reshape(6,4) # how many number i want in 3rd parameter : 24
a

array([[93, 28, 31, 14],
       [34, 68, 83, 26],
       [74, 51, 39, 68],
       [26, 85, 19, 67],
       [96, 96, 64, 88],
       [18, 12, 74, 62]], dtype=int32)

In [ ]:
# Find all numbers greater than 50

print(a > 50) # it gives boolean array
print(a[a > 50]) # it gives numbers more than 50

[[ True False False False]
 [False  True  True False]
 [ True  True False  True]
 [False  True False  True]
 [ True  True  True  True]
 [False False  True  True]]
[93 68 83 74 51 68 85 67 96 96 64 88 74 62]


In [27]:
# Find out even numbers

print(a[a % 2 == 0])

[28 14 34 68 26 74 68 26 96 96 64 88 18 12 74 62]


In [ ]:
# Find greater than 50 and are even

print(a[(a > 50) & (a % 2 == 0)]) # when work with boolean we have to use bitwise operators.
# like instead of and, we use &

[68 74 68 96 96 64 88 74 62]


In [ ]:
# Find all numbers not divisible by 7

print(a[a % 7 != 0])
# print(a[~(a % 7 == 0)]) we can write this as well

[93 31 34 68 83 26 74 51 39 68 26 85 19 67 96 96 64 88 18 12 74 62]
