# Broadcating 

-> the term broadcasting describes how NumPy treats arrays with different shapes during artithmetic operations

-> The smaller array is "broadcast" across the larger array so that they have compatible shapes.

In [4]:
# same shape

import numpy as np

a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [6]:
# diff shape

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


# Broadcasting Rules 

1. If the sizes of each dimension of the two arrays have the same number of dimensions.

>> if the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

2. Make the elements of the two arrays the same size

>> if the sizes of each dimension of the two arrays do not match, dimensons with size 1 are stretched to the size of the other array.

>> if there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [8]:
# more examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)
print(a + b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
a = np.arange(12).reshape(3,4) # it gives error
b = np.arange(3)

print(a)
print(b)
print(a + b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [10]:
a = np.arange(3).reshape(1,3) 
b = np.arange(3).reshape(3,1)

print(a)
print(b)
print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [14]:
a = np.arange(4).reshape(4,1) 
b = np.arange(3)

print(a)
print(b)
print(a + b)

[[0]
 [1]
 [2]
 [3]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [16]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)
print(a + b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]
