# Array Attributes

In [1]:
# numpy attributes
import numpy as np

arr1 = np.arange(10,dtype=np.int32)
arr2 = np.arange(12,dtype=float).reshape(3,4)
arr3 = np.arange(8).reshape(2,2,2)

arr3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
# ndim : tells you the number of dimensions (axes) of a NumPy array.

arr3.ndim

3

In [9]:
# shape : tells you how many elements are present in each dimension.

arr3.shape

(2, 2, 2)

In [12]:
# size : tells you the total number of elements present in a NumPy array.

print(arr2.size)
arr2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [11]:
# itemsize : tells you how many bytes are used to store ONE element of a NumPy array.

arr3.itemsize

8

In [ ]:
# dtype means data type

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
float64
int64


# Changing Data type

In [ ]:
# astype : used to convert the data type (dtype) of a NumPy array.

arr3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [16]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
# Scalar Opearations

print(a1 + 5)
print(a1 - 6)
print(a1 * 3)
print(a1 / 3)





[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[-6 -5 -4 -3]
 [-2 -1  0  1]
 [ 2  3  4  5]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
[[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]]


In [19]:
# Vector Operations 

""" In NumPy, vector operations mean performing mathematical operations
 directly on arrays/vectors without explicitly writing for loops. """

print(a1 + a2)
print(a2 - a1)
print(a1 * a2)
print(a1 / a2)



[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


# Numpy Array Functions

In [27]:
ar1 = np.random.random((3,3))
ar1 = np.round(ar1*100) # np.round() is used to round decimal numbers to a specified number of decimal places.
ar1 # by default it is 0 but we can decide as well like (array, decimal places)

array([[32., 28., 10.],
       [72., 22., 83.],
       [70., 79., 86.]])

In [ ]:
 # max, min, sum, prod

# max