### NUMPY BASICS 

In [ ]:
#How to create numpy array
import numpy as np

a = np.array([1,2,3]) # np.array  1D Array

print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
b = np.array([[1,2,3],[4,5,6]]) #2D Array
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [3]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #3D Array
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
# dtype

np.array([1,2,3],dtype = bool) #float #complex

array([ True,  True,  True])

In [5]:
#np.arange -- it works like range in for loop 

np.arange(1,11,2)



array([1, 3, 5, 7, 9])

In [6]:
# with reshape

np.arange(1,11).reshape(5,2) # 5 - rows, 2 - columns   # helps to create matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
# np.ones and np.zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# np.random

np.random.random((3,4))

array([[0.24297415, 0.83229827, 0.35006658, 0.18379936],
       [0.00688039, 0.23523068, 0.3657211 , 0.20724572],
       [0.27240491, 0.20044797, 0.52287516, 0.63476365]])

In [12]:
# np.linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
# np.identity

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])